cc_test(
    name = "add_binary_test",
    srcs = ["add_binary_test.cc",
            "add_binary.h"],
    copts = ["-Iexternal/googletest_git/googletest/include"],
    deps = ["//external:glog",
            "//external:gtest",
    ],
)
